version: '3'
services:
  dnsmasq:
    build: .
    container_name: dnsmasq-container
    environment:
      - TOR_DNS_SERVER=127.0.0.2    # You can adjust this value as needed
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped