version: '3'
services:
  dnsmasq:
    image: havenodex/dnsmasq:latest
    environment:
      - TOR_DNS_SERVER=127.0.0.2
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped